### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by eimi22** [Kesomannen/gale#321]
My friend installed the software before, and then he reinstalled the computer system. When he installed it again, he found that it crashed as soon as he opened it. Then he used Everything software to delete all files containing GALE, and the prompt popped up when he installed it again. Please help me, thank you.

![Image](https://github.com/user-attachments/assets/ec6bdbe4-df54-49fc-8bc9-d14bb7f40f96)

**Comment by Kesomannen** [comment]
What does the chinese/japanese line say?

**Comment by eimi22** [comment]
> 中文/日语台词说了什么？

The system cannot find the file specified

**Comment by Kesomannen** [comment]
Ok, go into `%appdata&/com.kesomannen.gale` and remove the `prefs.json` file and it should be fixed

**Comment by eimi22** [comment]
> 好的，进入`%appdata&/com.kesomannen.gale`并删除该`prefs.json`文件，它应该可以修复

I'll try it out later, thanks for your help

**Comment by eimi22** [comment]
> 好的，进入`%appdata&/com.kesomannen.gale`并删除该`prefs.json`文件，它应该可以修复

My friend said that the file was not found

**Comment by Kesomannen** [comment]
Oops, I misspelled the path, it's supposed to be `%appdata%/com.kesomannen.gale`. (The other one I sent had an ampersand instead of the second colon)

**Comment by YoBii** [comment]
I'm seeing the same error after updating from some rather old version of Gale.
It is resolved by deleting `prefs.json` but then when Gale has launched I can not switch to my games. When I try it says failed to create default profile, profile already exists. Renaming the default profile solves that, but then my actual profiles are still missing from the application. 

Should I maybe follow some incremental update strategy to avoid this?

**Comment by Kesomannen** [comment]
@YoBii If you're just updating, you should not remove the `prefs.json` file. Try to get that file back via the trashcan, otherwise your profiles might not be recoverable (at least not automatically). I should have clarified this better in my post.

The issue for you is likely something else but we can troubleshoot it further once you get the file back.

**Comment by YoBii** [comment]
@Kesomannen I have the file. 
For full clarity: This is all in a fresh Windows installation on a new drive. My old system drive is untouched and mounted as read-only. 
I copied over the AppData gale folder and installed the latest version. It would then fail to launch with the very error messaged displayed here in the OP. 
I'm not sure what the Gale version is that was installed on the old drive is but I can probably find out.
